"""The public coverage site: one static page over the generated cases, deployed with GitHub Pages.

Built offline from ``examples/<TICKER>/analysis.json`` and the files next to it (note, dashboard,
deck PDF, Excel model) plus the coverage log. It is a coverage page, not a marketing page: the
rating, the target and the agreement of the anchors for every company, links to the deliverables,
and the track record of every call the engine has made, with the return since initiation computed
from the log so a reader can check it.
"""
from __future__ import annotations

import datetime as dt
import json
import shutil
from pathlib import Path

from jinja2 import Template

from .. import __version__
from ..coverage import read_coverage
from .style import fmt_mult, fmt_num, fmt_pct

REPO = "https://github.com/oscarschjelderup-sketch/equity-research-engine"

TEMPLATE = Template(r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{ brand }} – coverage</title>
<style>
  :root { --navy: #003255; --blue: #81B0C0; --green: #407061; --red: #B03A2E; --grey: #8F9DA6; --light: #EEF1F4; --line: #D5DCE2; --text: #1d2733; }
  * { box-sizing: border-box; }
  body { margin: 0; background: #F6F8FA; color: var(--text); font-family: Arial, Helvetica, sans-serif; font-size: 14px; line-height: 1.45; }
  header { background: var(--navy); color: #fff; padding: 26px 28px 22px; }
  header h1 { font-family: Cambria, Georgia, serif; font-size: 30px; margin: 0 0 4px; font-weight: normal; }
  header .sub { color: #cfdbe4; font-size: 14px; }
  main { max-width: 1180px; margin: 0 auto; padding: 22px 16px 40px; }
  .card { background: #fff; border: 1px solid var(--line); border-radius: 6px; padding: 18px 20px; margin-bottom: 18px; }
  h2 { font-family: Cambria, Georgia, serif; color: var(--navy); font-size: 21px; margin: 0 0 10px; font-weight: normal; border-bottom: 2px solid var(--navy); padding-bottom: 6px; }
  p { margin: 8px 0; } a { color: var(--navy); }
  .wrap { overflow-x: auto; }
  table { border-collapse: collapse; width: 100%; font-size: 13px; }
  th, td { padding: 8px 9px; text-align: right; border-bottom: 1px solid var(--line); white-space: nowrap; }
  th { background: var(--navy); color: #fff; font-weight: bold; } td:first-child, th:first-child, td.l, th.l { text-align: left; }
  .badge { display: inline-block; font-weight: bold; color: #fff; padding: 3px 9px; border-radius: 3px; font-size: 12px; background: var(--grey); min-width: 52px; text-align: center; }
  .badge.BUY { background: var(--green); } .badge.SELL { background: var(--red); } .badge.HOLD { background: var(--grey); } .badge.NOT-RATED { background: #555; }
  .up { color: var(--green); font-weight: bold; } .down { color: var(--red); font-weight: bold; }
  .links a { margin-right: 10px; white-space: nowrap; }
  .muted { color: #6b7785; font-size: 12px; }
  .disc { background: #FFF6E5; border: 1px solid #F0D9A6; border-radius: 6px; padding: 12px 16px; font-size: 13px; margin-bottom: 18px; }
  details summary { cursor: pointer; color: var(--navy); font-weight: bold; margin: 8px 0; }
  footer { text-align: center; color: #6b7785; font-size: 12px; padding: 14px; border-top: 1px solid var(--line); }
  @media (max-width: 700px) { header h1 { font-size: 24px; } th, td { padding: 6px 6px; } }
</style></head>
<body>
<header><h1>{{ brand }}</h1><div class="sub">Equity research coverage · generated by the engine on {{ built }} · version {{ version }}</div></header>
<main>
  <div class="disc"><b>For illustration only – not investment advice.</b> Every page here is generated by an open-source valuation engine from public data
    (Yahoo Finance) and the assumptions in a case file. It is a portfolio project that shows the method; nothing on it is a recommendation to buy or sell any security.</div>
  <div class="card">
    <h2>Coverage</h2>
    <p>One command turns a ticker into a sell-side style investment case: a one-page research note, a deck with a six-slide appendix, an Excel model with live
      formulas and an interactive dashboard. The DCF is valued at today's date on the latest balance sheet; multiples are last twelve months and next twelve months on calendarised
      consensus; every case says how far its anchors – DCF, peers, consensus – agree. Method: <a href="{{ repo }}/blob/main/docs/methodology.md">methodology</a> ·
      code: <a href="{{ repo }}">GitHub</a>.</p>
    <div class="wrap"><table>
      <tr><th class="l">Company</th><th>Rating</th><th>Price</th><th>12m target</th><th>Upside</th><th>Total return</th><th>Anchors agree</th><th>EV/EBITDA LTM</th><th>vs peers</th><th>P/E NTM</th><th>Valued</th><th class="l">Deliverables</th></tr>
      {% for c in cases %}<tr>
        <td class="l"><b>{{ c.name }}</b> <span class="muted">{{ c.ticker }}{% if c.sector %} · {{ c.sector }}{% endif %}</span></td>
        <td><span class="badge {{ c.rating_css }}">{{ c.rating }}</span></td>
        <td>{{ c.ccy }} {{ c.price }}</td><td>{{ c.ccy }} {{ c.tp }}</td>
        <td class="{{ c.up_css }}">{{ c.upside }}</td><td>{{ c.total_return }}</td><td>{{ c.agreement }}</td>
        <td>{{ c.ev_ebitda }}</td><td>{{ c.vs_peers }}</td><td>{{ c.pe_ntm }}</td><td>{{ c.valued }}</td>
        <td class="l links">{% for lab, href in c.links %}<a href="{{ href }}">{{ lab }}</a>{% endfor %}</td>
      </tr>{% endfor %}
    </table></div>
    <p class="muted">Upside is to the 12-month target price; total return adds the expected dividend. "Anchors agree" is the engine's own cross-check of the DCF against
      peer multiples and consensus (high / medium / low). vs peers: EV/EBITDA against the peer median.</p>
  </div>
  <div class="card">
    <h2>Track record</h2>
    {% if track %}
    <div class="wrap"><table>
      <tr><th class="l">Company</th><th>First rated</th><th>Call</th><th>Price then</th><th>Target then</th><th>Latest price</th><th>Return since</th><th>Updates</th><th>Current call</th></tr>
      {% for t in track %}<tr>
        <td class="l"><b>{{ t.name }}</b> <span class="muted">{{ t.ticker }}</span></td><td>{{ t.first_date }}</td>
        <td><span class="badge {{ t.first_rating_css }}">{{ t.first_rating }}</span></td><td>{{ t.ccy }} {{ t.first_price }}</td><td>{{ t.ccy }} {{ t.first_tp }}</td>
        <td>{{ t.ccy }} {{ t.last_price }}</td><td class="{{ t.ret_css }}">{{ t.ret }}</td><td>{{ t.n }}</td>
        <td><span class="badge {{ t.last_rating_css }}">{{ t.last_rating }}</span> {{ t.ccy }} {{ t.last_tp }}</td>
      </tr>{% endfor %}
    </table></div>
    <p class="muted">Return since the first rating is the share price change only (no dividends), from the log the engine writes on every run. It is here so the calls can be checked, including the wrong ones.</p>
    <details><summary>Full log ({{ log|length }} entries)</summary><div class="wrap"><table>
      <tr><th class="l">Date</th><th class="l">Ticker</th><th>Rating</th><th>Price</th><th>Target</th><th>Fair value</th><th>Total return</th><th>Anchors</th><th>Consensus TP</th><th>Version</th></tr>
      {% for r in log %}<tr><td class="l">{{ r.date }}</td><td class="l">{{ r.ticker }}</td><td><span class="badge {{ r.rating_css }}">{{ r.rating }}</span></td>
        <td>{{ r.price }}</td><td>{{ r.target_price }}</td><td>{{ r.fair_value }}</td><td>{{ r.total_return }}</td><td>{{ r.agreement }}</td><td>{{ r.consensus_target }}</td><td>{{ r.engine_version }}</td></tr>{% endfor %}
    </table></div></details>
    {% else %}<p class="muted">No calls logged yet.</p>{% endif %}
  </div>
</main>
<footer>{{ brand }} · built {{ built }} · <a href="{{ repo }}">source</a> · For illustration only – not investment advice</footer>
</body></html>
""")


def _css(rating: str) -> str:
    return str(rating or "").replace(" ", "-")


def _case_summary(ticker: str, d: dict, files: dict[str, str]) -> dict:
    co, rec = d["company"], d["recommendation"]
    cc = d.get("crosscheck") or {}
    comp = (d.get("comps") or {}).get("company") or {}
    stats = (d.get("comps") or {}).get("stats") or {}
    med = (stats.get("All|median") or {}).get("ev_ebitda")
    own = comp.get("ev_ebitda")
    up = rec.get("upside")
    return {
        "ticker": ticker, "name": co.get("name") or ticker, "sector": co.get("industry") or co.get("sector") or "",
        "rating": rec.get("rating", ""), "rating_css": _css(rec.get("rating", "")), "ccy": co.get("price_currency") or co.get("currency") or "",
        "price": fmt_num(co.get("price"), 2), "tp": fmt_num(rec.get("target_price"), 2) if rec.get("rating") != "NOT RATED" else "n.a.",
        "upside": fmt_pct(up, 0, sign=True), "up_css": ("up" if (up or 0) >= 0 else "down") if up is not None else "",
        "total_return": fmt_pct(rec.get("total_return"), 0, sign=True), "agreement": (cc.get("agreement") or "n/a").capitalize(),
        "ev_ebitda": fmt_mult(own), "vs_peers": fmt_pct(own / med - 1, 0, sign=True) if (own and med) else "–", "pe_ntm": fmt_mult(comp.get("fwd_pe")),
        "valued": (d.get("valuation_date") or d.get("as_of") or "")[:10],
        "links": [(lab, href) for lab, href in (("Note (PDF)", files.get("note_pdf")), ("Note", files.get("note_html")), ("Dashboard", files.get("dashboard")),
                                                ("Deck (PDF)", files.get("deck_pdf")), ("Model (xlsx)", files.get("model"))) if href],
        "_price": co.get("price"),
    }


def _track_record(log: list[dict], cases: dict[str, dict]) -> list[dict]:
    out = []
    for ticker in sorted({r["ticker"] for r in log}):
        rows = sorted((r for r in log if r["ticker"] == ticker), key=lambda r: r["date"])
        first, last = rows[0], rows[-1]
        latest_price = cases[ticker]["_price"] if ticker in cases and cases[ticker].get("_price") else float(last["price"])
        p0 = float(first["price"])
        ret = latest_price / p0 - 1 if p0 else None
        out.append({"ticker": ticker, "name": cases.get(ticker, {}).get("name") or first.get("name") or ticker, "ccy": first.get("currency", ""),
                    "first_date": first["date"], "first_rating": first["rating"], "first_rating_css": _css(first["rating"]),
                    "first_price": fmt_num(p0, 2), "first_tp": fmt_num(float(first["target_price"]) if first.get("target_price") else None, 2),
                    "last_price": fmt_num(latest_price, 2), "ret": fmt_pct(ret, 1, sign=True), "ret_css": ("up" if (ret or 0) >= 0 else "down") if ret is not None else "",
                    "n": len(rows), "last_rating": last["rating"], "last_rating_css": _css(last["rating"]),
                    "last_tp": fmt_num(float(last["target_price"]) if last.get("target_price") else None, 2)})
    return out


def build_site(cases_dir: str | Path = "examples", out_dir: str | Path = "site", coverage_csv: str | Path = "coverage/history.csv",
               brand: str | None = None) -> Path:
    cases_dir, out_dir = Path(cases_dir), Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / ".nojekyll").write_text("", encoding="utf-8")
    summaries: dict[str, dict] = {}
    for case_dir in sorted(p for p in cases_dir.iterdir() if p.is_dir() and (p / "analysis.json").exists()):
        t = case_dir.name
        d = json.loads((case_dir / "analysis.json").read_text(encoding="utf-8"))
        dest = out_dir / "cases" / t
        dest.mkdir(parents=True, exist_ok=True)
        files: dict[str, str] = {}
        for key, name in (("note_pdf", f"{t}_note.pdf"), ("note_html", f"{t}_note.html"), ("dashboard", f"{t}_dashboard.html"),
                          ("deck_pdf", f"{t}_deck.pdf"), ("model", f"{t}_model.xlsx")):
            src = case_dir / name
            if src.exists():
                shutil.copyfile(src, dest / name)
                files[key] = f"cases/{t}/{name}"
        shutil.copyfile(case_dir / "analysis.json", dest / "analysis.json")
        summaries[t] = _case_summary(t, d, files)
        brand = brand or ((d.get("config") or {}).get("brand") or {}).get("name")
    log = read_coverage(coverage_csv)
    for r in log:
        r["rating_css"] = _css(r.get("rating", ""))
        r["price"] = fmt_num(float(r["price"]), 2) if r.get("price") else ""
        r["fair_value"] = fmt_num(float(r["fair_value"]), 2) if r.get("fair_value") else ""
        r["total_return"] = fmt_pct(float(r["total_return"]), 0, sign=True) if r.get("total_return") else ""
    order = {"BUY": 0, "HOLD": 1, "SELL": 2}
    cases = sorted(summaries.values(), key=lambda c: (order.get(c["rating"], 3), c["name"]))
    html = TEMPLATE.render(brand=brand or "Equity Research Engine", built=dt.date.today().isoformat(), version=__version__, repo=REPO,
                           cases=cases, track=_track_record(log, summaries), log=list(reversed(log)))
    (out_dir / "index.html").write_text(html, encoding="utf-8")
    return out_dir
